### ISSUE TITLE
Cryptographic Primitives for Smart Contracts

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-rust-smart-contracts#103]
In order to make it more cost effective to do some basic cryptographic operations that are needed for certain applications we need to add them as primitives to contracts.

This is a minimal version to be included in Sirius for immediate needs of upcoming use-cases.

These primitives are
- ed25519 signature checking
- ecdsa over secp256k1 signature checking (bitcoin/ethereum scheme)
- sha2-256 hashing
- sha3-256 hashing
- keccak-256 hashing (this is almost sha3, but with a padding difference, it is what Ethereum uses in their smart contracts, hence the motivation).

**Comment by abizjak** [comment]
This issue is also a part of the epic https://github.com/Concordium/concordium.github.io/issues/451

**Comment by dg-concordium** [comment]
@Bargsteen and @abizjak will this be a separate pull request from the smart contracts v1 documentation or included in that PR?

**Comment by abizjak** [comment]
It is orthogonal to the changes that are already there so it would be natural for it to be a separate PR.
