### ISSUE TITLE
Returning funds immediately when outbidded by another bid (this will prevent having to use loops that can run out of gas)

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-rust-smart-contracts#112]
**Description**
`Loops` can run out of gas in smart contracts, therefore they are used very rarely in smart contracts (only when we can ensure that we are in control of the size of the object that the loop is iterating through).

Example when loops can be used safely:
If the owner of a smart contract adds addresses to a list, then it is perfectly fine to iterate via a for loop over this list since we can assume that the owner of the smart contract is a smart contract developer and knowledgable enough to not insert too many addresses in the list. 

Example when loops should be avoided:
If a general user calls our smart contract and this action causes an e.g. address to be inserted in a list then we don't have any control of the size of the list anymore. If our smart contract protocol becomes super popular the list can grow significantly. In addition, competitor protocols might on purpose call this function to blow up our list so that any loop that iterates through the list in our smart contract is now reverting (parts of our protocol become inexecutable).

Suggestion for the [auction example](https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/auction/src/lib.rs):
Since the payout function of the auction example iterates via a for loop over an object that was grown in size by user actions, we should safeguard that the size of the object does not grow too large. This is to prevent the smart contract to be unable to pay out its rewards (causing the funds to be stuck in the smart contract).

1. STEP: Adding a variable `MAX_PARTICIPANTS` :

    **const MAX_PARTICIPANTS: u32 = 100;**

2. STEP: Adding a counter of how many addresses/users/bids already participated in our auction:

     /// Number of bids in the StateMap bids
    **number_of_bids: u32**
 
 3. STEP: Checkinging in the `bid` receive funciton that we are not inserting too many addresses
        **ensure!(MAX_PARTICIPANTS >= state.viewable_state.number_of_bids,
        BidError::MaxParticipantsReached);**
        
Please remove the label "question" if it is ok that I work on it or close the issue to reject the suggested changes.

**Comment by abizjak** [comment]
I am not sure what if anything should be done here.

On the one hand this auction is not really useful in the current scope. It is a toy example so from that perspective I do not wish to complicate it more. It would make sense to maybe add a comment to this effect though.

On the other hand energy use is of course something programmers must take care of. The solution that is proposed is not adequate in my view though. A better solution would be to just keep track of the highest bid and just return bids that are replaced by the next highest bid. Then there are never any loops and arbitrary bounds. This perhaps increases the cost of bidding, but that is not a given either.

The proposed solution hardcodes the bound, but in reality the bound should probably depend on the value being sold. Moreover the proposed solution has the wrong incentive. If I am an attacker then what I can do is just make tiny bids upfront that fills up the allocated number of bids. Then the seller won't get what they want. If we want to store multiple bids then we should kick the lowest bid out (transfer back).

**Comment by DOBEN** [comment]
Yes, I agree. The best way would be that we only keep the funds from one user in the smart contract locked (the highest bidding user) and whenever somebody places a higher bid we return the old funds from the previous highest bidder and locked the funds from the new highest bidder.

**Comment by abizjak** [comment]
Ok, if you change it in this way then I think it'll make the contract simpler or at least not more complicated. I support that.
