### ISSUE TITLE
Tutorial for building off-chain tools that interact with the chain

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-rust-smart-contracts#115]
**Task description**

Create a tutorial that shows the user how to create an off-chain tool that interacts with the chain via one of our SDKs.
This could, for example, be a tool that runs several times a day, fetches the weather for a given location, and updates the weather oracle in the icecream example contract: 
https://github.com/Concordium/concordium-rust-smart-contracts/blob/20356a72c4bed0708374aa1e92ec29ddb4ed786e/examples/icecream/src/lib.rs#L165

**Comment by smh1001** [comment]
Closing this since a tutorial has been created for wccd token in this issue
[https://github.com/Concordium/concordium-rust-smart-contracts/issues/131](https://github.com/Concordium/concordium-rust-smart-contracts/issues/131)
