### ISSUE TITLE
Concordium development for Ethereum developers

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-rust-smart-contracts#124]
We will start by looking at the differences between Ethereum smart contract development and Concordium and then move on to differences between doing off chain services also.

Was:
Smart contract approval allowance mechanism (Approving Allowances means authorizing the smart contract, in advance, to spend the tokens, without needing the private key to do that). ERC-20 has the TransferFrom method which does this. Source: Tacans

**Comment by abizjak** [comment]
In light of the discussions we have had recently, should this epic be revised?

We seemed to have agreed in an email exchange that they are OK without approvals.

@smh1001 @limemloh

**Comment by limemloh** [comment]
We have added a paragraph about `TransferFrom` in CIS-2, because of this.
There is already a section about what we have instead of allowance.
