### ISSUE TITLE
concordium-std improvements

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-rust-smart-contracts#133]
concordium-std has been updated to V1 smart contracts but there are a number of opportunities for improvement both in performance (reducing code size, reducing complexity) as well as adding functionality.  Programmer/user ergonomics are key for anything here, so a large part of any improvement must be design considerations.

- Add ability to return error messages from init/receive entrypoints. This is not currently possible with concordium-std, but the chain allows it.
- Integrate these return values into the schemas and allow them to be pretty printed by the client.

**Comment by abizjak** [comment]
So there is already an epic https://github.com/Concordium/concordium-rust-smart-contracts/issues/126 for this.

I don't get why it does not show on the zenhub board.

**Comment by abizjak** [comment]
It does show now, so I am closing this one.
