### ISSUE TITLE
`address` and `owner` variables are swapped around in the `OperatorOf` functions of the cis2 tokens. 

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-rust-smart-contracts#135]
**Bug Description**

When querying the operator then the `owner` and `address` variables are swapped around. This means that the ‘OperatorOf’ function returns a wrong value. 

fn is_operator(&self, address: &Address, owner: &Address) -> bool
https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/cis2-wccd/src/lib.rs#L161

let is_operator = host.state().is_operator(&query.owner, &query.address);
https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/cis2-wccd/src/lib.rs#L580

**Comment by abizjak** [comment]
Good catch.
