### ISSUE TITLE
Build interface registry smart contract

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-rust-smart-contracts#139]
Write and test an interface registry smart contract similar to [EIP-1820](https://eips.ethereum.org/EIPS/eip-1820) found on Ethereum.

Each chain (mainnet and testnet) should have a single instance of this smart contract. This instance acts as a global registry, allowing other smart contracts to register their supported standards. 
This registry can then be queried by dapps for discovering smart contracts implementing certain standards.

It should:
- Log an event, when a contract register implementing some standard.
- Allow other smart contracts to add “managers“, which are accounts or contract with permission to register standards on behalf of the smart contract.
  - By default, only the smart contract itself is allowed to register information.
  - An event is logged when a contract updates its managers.
- Allow a smart contract to register another smart contract address as the “implementor” of some standard for itself. 
  This is useful for adding support for a new standard through another smart contract or support two standards incompatible standards.
- Unlike EIP-1820, the registry should _not_ fall back to using EIP-165 and instead fail to provide the information.
- The registry is expected to be deployed behind a proxy.

Additionally, the CIS-2 smart contract examples should implement an endpoint for registering.

**Comment by abizjak** [comment]
Shouldn't we close this for now?

**Comment by limemloh** [comment]
Closing this issue, since currently there are no plans to implement this.
