### ISSUE TITLE
Document interface registry usage and deployment information

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-rust-smart-contracts#140]
Add documentation for how to interact with smart contract interface registry.
See https://github.com/Concordium/concordium-rust-smart-contracts/issues/139.

It could include:
- [ ] Describe the events logged and serialization.
- [ ] How to invoke the query function contract off-chain and on-chain.
- [ ] How to register an implementation of a standard for your smart contract.
- [ ] How to set up managers for your smart contract.
- [ ] How managers register an implementation of a standard for a smart contract.
- [ ] Document the contract address on mainnet and testnet with the registry.

**Comment by abizjak** [comment]
Shouldn't we close this for now?

**Comment by limemloh** [comment]
Closing this issue, since currently there are no plans to implement this.
