### ISSUE TITLE
Fix auction example

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-rust-smart-contracts#149]
**Bug Description**

The auction example was written by setting the `self_balance` in the `TestHost` to the `smart contract balance` instead of the `smart contract + amount balance` as described [here](https://docs.rs/concordium-std/latest/concordium_std/test_infrastructure/struct.TestHost.html#method.set_self_balance)

`Set the contract balance. NB: This should be the sum of the contract’s initial balance and the amount you wish to invoke it with.`

As a result, also the balance logic in the smart contract was written assuming that `self_balance` does not account for the `amount` which is a wrong assumption as can be seen [here](https://docs.rs/concordium-std/latest/concordium_std/trait.HasHost.html#tymethod.self_balance)

The auction example does not work when deployed on testnet at the moment.

**Expected Result**
Smart contract passes all test cases and should work on testnet.

**Actual Result**
Smart contract passes all test cases BUT DOES NOT WORK on testnet.

**Comment by abizjak** [comment]
Any chance you would just ahead and fix this? :)
