### ISSUE TITLE
Schema bug in the `Receiver`

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-rust-smart-contracts#153]
**Bug Description**
Calling the `wrap` function on the wCCD smart contract with `sender != receiver` (The `Receiver` is a smart contract and not an account) fails with the following error `'wrap' in 'CIS2-wCCD-Proxy' at {"index":792,"subindex":0} failed with code -2147483627`

The requested schema is quite weird as follows:

> {
>     "data": "",
>     "to": {
>         "Contract": [
>            {
>                "index": 843,
>                "subindex": 0
>             },
>            {
>                "contract": "auction",
>                "func": "receiveToken"
>            }
>        ]
>    }
> }

Investigation by Emil:
A bug in the schema type for `Receiver` causes this behavior. The Receiver uses `OwnedEntrypointName` but the schema uses `OwnedReceiveName`.

Solution by Emil:
Replacing the `OwnedReceiveName` [here](https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/concordium-cis2/src/lib.rs#L839) with `schema::Type::String(schema::SizeLength::U16)`

The suggested solution was tested on testnet with the `wCCD` token and worked.

**Expected Result**

The `wrap` call should not fail when `Receiver` is a smart contract.

**Actual Result**

The `wrap` call fails when `Receiver` is a smart contract.

**Comment by abizjak** [comment]
Good catch.
