### ISSUE TITLE
Issues in the piggy bank smart contract testing tutorial 

### ISSUE THREAD

**Issue by hamiidreza** [Concordium/concordium-rust-smart-contracts#159]
**Description**
If you follow the tutorial for piggy bank smart contract testing [here](https://developer.concordium.software/en/mainnet/smart-contracts/tutorials/piggy-bank/testing.html#piggy-bank-testing), you might get a compiling error saying the function TestHost::new() should take 2 arguments, but it takes only 1. In fact, the second argument "TestStateBuilder::new()" turns out to be missing in the tutorial. 
Further, the tutorial has only 4 tests, whereas [the Github code](https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/piggy-bank/part2/src/lib.rs) has 8 tests including the following ones as well:
- test_insert_smashed() 
- test_smash_account_missing()
- test_smash_smashed()
- test_view()

**Steps to Reproduce**

**Expected Result**

**Actual Result**

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by abizjak** [comment]
Regarding tests, we added some recently.

Would you be willing to fix the bugs in documentation though? The ones regarding `TestStateBuilder::new`?

**Comment by hamiidreza** [comment]
Sure. I will make a pull request with the fix by today.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hamiidreza** [comment]
done.
