### ISSUE TITLE
Change name for crate if it is possible

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-rust-smart-contracts#172]
**Description**
Mentioning crate in the generation tool user interface could be confusing for users who don't know Rust concepts. Examples:
- Using the generation tool offers to name the Project and afterwards asks for the description of a crate
- If user writes unsuitable name for a Project, error is thrown because it is not suitable for 'crate'

Maybe just offer to the users to name the project and add description of a project (avoid word crate).

![image](https://user-images.githubusercontent.com/98821384/195269738-0ee49e38-8543-4705-a1d4-98eff60b83bf.png)

**Comment by DOBEN** [comment]
- The thrown error about the wrong `crate name` is part of `cargo-generate` and we cannot change it easily to use `project name` instead.

- I will fix the question to use `Description for the project?` instead because this is part of our template and can be fixed easily.
