### ISSUE TITLE
Add a "CIS2Client" to the concordium-cis2 library

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-rust-smart-contracts#295]
**Task description**

We have a CIS2Contract client in the SDK that wraps the low-level invoke to provide a type-safe interface to any CIS2 contract.

Since invoking transfers and other CIS2 operations also happen inside contracts we should add similar "CIS2Client" to the concordium-cis2 library to ease writing contracts that interact with CIS2 tokens.

**Comment by parv0888** [comment]
Raise a PR to address this Issue
https://github.com/Concordium/concordium-rust-smart-contracts/pull/304

**Comment by abizjak** [comment]
Fixed by #304
