### ISSUE TITLE
Templates are always taken from `main`

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-rust-smart-contracts#331]
**Task description**

```
cargo concordium init
```

always takes the templates from `main`. This is a bit problematic since we often have unreleased changes on main and it is awkward to make those without breaking  something.

Instead of defaulting to main, we should specify a tag in `cargo generate` invocation.

We should support a special `template/latest` tag that we'd update each time we release new concordium-std, and this should be the default tag, and then we should also support normal release tags, e.g., `concordium-std/7.1.0`.

This would also make it simpler for us to develop.

**Comment by abizjak** [comment]
@DOBEN @limemloh Any thoughts?

**Comment by limemloh** [comment]
Seems like a reasonable approach, maybe even have template releases separate from `concordium-std` such that we can update these without updating `concordium-std`.

**Comment by rasmus-kirk** [comment]
Solved with #419 and [this](https://github.com/Concordium/concordium-smart-contract-tools/pull/163)
