### ISSUE TITLE
Combine the `set_size_length`, `map_size_length`, `size_length` into one field attribute.

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-rust-smart-contracts#38]
**Description**
The proc-macro for deriving Serial have multiple field attributes for setting the `size_length` depending on what type of collection you set it on.

It would be nice to only have one attribute, removing `set_size_length`, `map_size_length` and `string_size_length`.

**Comment by concordium-cl** [comment]
@Bargsteen: Please update.

**Comment by Bargsteen** [comment]
Closed by https://github.com/Concordium/concordium-rust-smart-contracts/pull/39
