### ISSUE TITLE
Standardize a way for smart contracts to log memos

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-rust-smart-contracts#55]
**Task description**

Provide a standard template on how a smart contract should immitate a memo feature when doing transfers to accounts.

The transfer message cannot contain any metadata in addition to the amount. But a contract can omit events. The task is to define the format of events that will serve the same purpose as the memo field of a a transfer with metadata.

- [ ] Define the format.
- [ ] Provide a not-entirely-trivial example of a contract in the examples folder.

**Comment by limemloh** [comment]
This would be nice to have, but I will close this until we have some use cases for building the actual requirements.
