### ISSUE TITLE
Better support for return values for failures.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-rust-smart-contracts#78]
**Task description**

With the introduction of synchronous calls in #71 contracts can return values now, even if they fail due to a logic error.
However the support for this in concordium-std is limited. We only support it via manually implementing `Into<Reject>` for your chosen error type, and to implement this one needs to produce a Vec<u8>. This is less ergonomic than our other support, where we do serialization behind the scenes.

This is related to #71 . It is not blocking for it, but it will likely need some API changes in the library, so it would be good to have it done before release.

**Comment by Bargsteen** [comment]
Closed by https://github.com/Concordium/concordium-rust-smart-contracts/pull/145
