### ISSUE TITLE
Parameter is ambiguous name

### ISSUE THREAD

**Issue by XuHugo** [Concordium/concordium-rust-smart-contracts#85]
**Bug Description**
When I compiled with the latest version of concordium trust smart contracts, an error occurred. I found that Parameter is a conflicting variable because it is in concordium-std\type.rs and concordium-contract-common\type.rs has a definition.
We're at concordium-std\impl.rs uses a Parameter, which makes the compiler unable to know which parameter we want to use.

**Steps to Reproduce**

**Expected Result**

**Actual Result**
   ### _Compiling concordium-std v2.0.0 (D:\contract2\concordium-rust-smart-contracts-main\concordium-rust-smart-contracts-main\concordium-std)
error[E0659]: `Parameter` is ambiguous (glob import vs glob import in the same module)
   --> D:\contract2\concordium-rust-smart-contracts-main\concordium-rust-smart-contracts-main\concordium-std\src\impls.rs:274:15
    |
274 | impl Read for Parameter {
    |               ^^^^^^^^^ ambiguous name
    |
note: `Parameter` could refer to the struct imported here
   --> D:\contract2\concordium-rust-smart-contracts-main\concordium-rust-smart-contracts-main\concordium-std\src\impls.rs:12:5
    |
12  | use concordium_contracts_common::*;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `Parameter` to disambiguate
note: `Parameter` could also refer to the struct imported here
   --> D:\contract2\concordium-rust-smart-contracts-main\concordium-rust-smart-contracts-main\concordium-std\src\impls.rs:8:5
    |
8   |     types::*,
    |     ^^^^^^^^
    = help: consider adding an explicit import of `Parameter` to disambiguate

error[E0659]: `Parameter` is ambiguous (glob import vs glob import in the same module)
   --> D:\contract2\concordium-rust-smart-contracts-main\concordium-rust-smart-contracts-main\concordium-std\src\impls.rs:289:23
    |
289 | impl HasParameter for Parameter {
    |                       ^^^^^^^^^ ambiguous name
    |
note: `Parameter` could refer to the struct imported here
   --> D:\contract2\concordium-rust-smart-contracts-main\concordium-rust-smart-contracts-main\concordium-std\src\impls.rs:12:5
    |
12  | use concordium_contracts_common::*;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `Parameter` to disambiguate
note: `Parameter` could also refer to the struct imported here
   --> D:\contract2\concordium-rust-smart-contracts-main\concordium-rust-smart-contracts-main\concordium-std\src\impls.rs:8:5
    |
8   |     types::*,
    |     ^^^^^^^^
    = help: consider adding an explicit import of `Parameter` to disambiguate_

**Versions**
- Software Version
  concordium-std= “2.0.0”
 concordium-contracts-common = “2.0”

- OS   
  windows

- Browser
- Mobile device, if applicable

**Comment by abizjak** [comment]
Hi, sorry for the late response.

It looks like you are using the unreleased version of the libraries. I believe the released version works correctly.

We are in the middle of substantial changes for the next release of the library, so the concordium-contracts-common and concordium-std are at the moment slightly out of sync in their repositories.

Do you need to use unreleased versions of libraries?
