### ISSUE TITLE
Make non-reentrant mock functions the default

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-rust-smart-contracts#89]
**Description**

Currently, `MockFn::new[_v0, _v1]` gets the `&mut Amount` and `&mut State` parameters so that you can mock contracts that use reentrancy (contracts that call themselves, either directly or transitively).

I propose that we simplify the API by renaming the `MockFn::new[_v0, _v1]` methods to `*_reentrancy` (or similar) and add new some new`MockFn::new[_v0, _v1]` methods that do not have the `&mut Amount` and `&mut State` parameters, thereby making the simpler version the "default".

The new methods should thus be:
- `new`-variants will expect a closure of `|Parameter, Amount| -> Result<..>
- `new_reentracy`-variants will expect a closure of `|Parameter, Amount, &mut Amount, &mut State| -> Result<..>`

**Comment by abizjak** [comment]
Since we are deprecating the test host and migrating to use the testing library I am closing this.
