### ISSUE TITLE
Make v1 mock functions the default

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-rust-smart-contracts#90]
**Description**

Currently, there are three new functions for `MockFn` in the testing infrastructure.
`new` which can mock both v0 and v1 functions.
`new_V1` which only mocks v1 (always has a return value on success)
`new_v0` which only mocks v0 (never has a return value)

I propose that we make `v1` contracts the default, so we have
`new` which only mocks v1 contracts.
`new_v0` which only mocks v0 contracts.

**Comment by abizjak** [comment]
Since we are migrating away from the "Test Host" to use the integration testing library I am closing this.
